### ISSUE TITLE
propagate updates to denormalized vocabularies

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-vocabularies#154]
When a vocabulary is updated (i.e. `ServiceWriter(update=True)`), the denormalized values of the records that link said vocabulary should also be updated.

- How to obtain the corresponding records (i.e. how to ES query the `@v` field)?. Find a query that is able to handle the structure `uuid::version`. Since we are going to do it programatically, we should consider not using querystring and using [regex](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html) and [range](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html) queries.
 An example of the querystring (not working): 
```
http :9200/rdmrecords-records-record-v4.0.0/_search 'q==metadata.resource_type.@v:/8d381135-727b-4480-8630-1ae9c88e7e1e::.*/ AND metadata.resource_type.@v:<="8d381135-727b-4480-8630-1ae9c88e7e1e::0"'
```
- How do we re-index the records? Denormalized values are not stored in DB, they can potentially be "just" re-indexed in ES. This would break the current service level definitions.
- Can we group updates to avoid re-indexing a record multiple times (e.g. in the case of multiple subjects being updated)? This would mean that we have to store temporarily the updated vocabularies (Redis?)

**Comment by lnielsen** [comment]
My 2 cents. 

- The ``@v`` property works well to find all related records for a single vocabulary record. I don't think it works well for find all related records for a set of vocabulary records.

The query would be something like:

```
metadata.resource_type.id="{vocab.id}" 
AND NOT metadata.resource_type.@v:"{vocab.id}::{vocab.revsion}"
```

Related to concurrency then it should work fine, because even if we identify a record that might not need being updated, it's ok to reindex it since it will always index with the latest version of the vocab record.

Regarding avoiding re-indexing a record multiple times it might be difficult, and could be an later optimisation. The problem has some resemblance with an URL/Crawl frontier.

**Comment by lnielsen** [comment]
Also for the original considerations: https://codimd.web.cern.ch/XfEvnoWrRKuKhf0N3glfjA#Finding-outdated-dereferenced-relations

**Comment by ppanero** [comment]
closed in favour of https://github.com/inveniosoftware/invenio-records-resources/issues/322
